Repository uqfoundation/dill, pull requests merged in 2022-07, with the labels that each got.

#471 Add detailed trace mode showing saved object size and visual depth level
  README.md
  dill/__init__.py
  dill/_dill.py
  dill/detect.py
  dill/logger.py
  tests/test_logger.py
Labels: enhancement

#496 Rewrite _create_code() with Structural Pattern Matching (limited to tuples)
  dill/_dill.py
  dill/tests/test_functions.py
Labels: refactor

#524 Fix tox tests so they will actually fail
  dill/tests/__main__.py
  tox.ini
Labels: bugfix

#526 fix dump_module() bugs and rename parameter 'main' to 'module'
  .gitignore
  dill/_dill.py
  dill/tests/test_session.py
Labels: bugfix

#503 A temporary quick fix for dataclass serialization (#500)
  dill/_dill.py
  dill/_objects.py
  dill/tests/test_dataclasses.py
Labels: enhancement

#530 Move session-related code to new session module
  dill/__init__.py
  dill/_dill.py
  dill/session.py
  dill/tests/test_session.py
  docs/source/dill.rst
Labels: refactor

#531 Temporary quick fix for getsource() on IPython interpreter (fixes #346)
  dill/_dill.py
  dill/source.py
Labels: compatibility
