Repository uqfoundation/dill, pull requests merged in 2022-08, with the labels that each got.

#529 Fix pickling errors thrown when saving some Stdlib modules
  dill/_dill.py
  dill/tests/test_classdef.py
Labels: enhancement

#538 Fix `pickles()` flagging `__builtins__` as unpickleable due to the `all()` function
  dill/_dill.py
Labels: bugfix

#539 Use proper SPDX identifier for License
  setup.py
Labels: compatibility

#541 Disable logging propagation, use current stderr as output
  dill/logger.py
Labels: enhancement

#542 Optimize the numpy hook
  dill/_dill.py
  dill/logger.py
  dill/tests/test_classdef.py
  dill/tests/test_weakref.py
Labels: enhancement

#535 Minor type fix
  dill/session.py
Labels: compatibility
