Repository uqfoundation/dill, pull requests merged in 2024-01, with the labels that each got.

#638 updated copyright for 2024
  LICENSE
  dill/__diff.py
  dill/__init__.py
  dill/_dill.py
  dill/_objects.py
  dill/_shims.py
  dill/detect.py
  dill/logger.py
  dill/objtypes.py
  dill/pointers.py
  dill/session.py
  dill/settings.py
  dill/source.py
  dill/temp.py
  dill/tests/__init__.py
  dill/tests/__main__.py
  dill/tests/test_abc.py
  dill/tests/test_check.py
  dill/tests/test_classdef.py
  dill/tests/test_dataclasses.py
  dill/tests/test_detect.py
  dill/tests/test_dictviews.py
  dill/tests/test_diff.py
  dill/tests/test_extendpickle.py
  dill/tests/test_fglobals.py
  dill/tests/test_file.py
  dill/tests/test_functions.py
  dill/tests/test_functors.py
  dill/tests/test_logger.py
  dill/tests/test_mixins.py
  dill/tests/test_module.py
  dill/tests/test_moduledict.py
  dill/tests/test_nested.py
  dill/tests/test_objects.py
  dill/tests/test_properties.py
  dill/tests/test_pycapsule.py
  dill/tests/test_recursive.py
  dill/tests/test_registered.py
  dill/tests/test_restricted.py
  dill/tests/test_selected.py
  dill/tests/test_session.py
  dill/tests/test_source.py
  dill/tests/test_temp.py
  dill/tests/test_weakref.py
  scripts/get_gprof
  scripts/get_objgraph
  scripts/undill
  setup.py
  version.py
Labels: compatibility

#629 Import submodule properly when there is an attribute of the module with the same name
  dill/_dill.py
Labels: bugfix

#641 update sphinx to 6.2.1
  docs/requirements.txt
Labels: dependencies

#644 skip BufferedRandomType on pyodide
  .travis.yml
  dill/_dill.py
Labels: compatibility

#645 further skip BufferedRandomType if does not exist
  dill/_objects.py
  dill/tests/test_selected.py
  setup.cfg
Labels: compatibility

#646 remove stray import of dbm in objects
  dill/_objects.py
Labels: compatibility
